version: '3.1'

services:
  world_x:
    image: mysql
    environment:
      MYSQL_DATABASE: 'demo_students_db' # make sure it's surrounded by single quotes
      MYSQL_ROOT_PASSWORD: '@Ndy021003'
    ports:
      - "3333:3306"
    expose:
      - '3333'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-volume: